npmScopes:
  "@react-native-google-signin":
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: "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"

npmRegistryServer: "https://registry.npmjs.org"

npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: "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"
